service: python-serverless-arch1-yldevier

provider:
  name: aws
  runtime: python3.12
  region: ap-southeast-1
  environment:
    DYNAMODB_TABLE: ${self:service}
  role: arn:aws:iam::956304645529:role/serverless-app-role

functions:
  createLoyaltyCard:
    handler: handler.create
    events:
      - httpApi:
          path: /loyalty-cards
          method: post

  getAllLoyaltyCards:
    handler: handler.get_all
    events:
      - httpApi:
          path: /loyalty-cards
          method: get

  getLoyaltyCard:
    handler: handler.get_one
    events:
      - httpApi:
          path: /loyalty-cards/{id}
          method: get

  updateLoyaltyCard:
    handler: handler.update
    events:
      - httpApi:
          path: /loyalty-cards/{id}
          method: put

  deleteLoyaltyCard:
    handler: handler.delete
    events:
      - httpApi:
          path: /loyalty-cards/{id}
          method: delete

  batchCreateLoyaltyCards:
    handler: handler.batch_create_loyalty_cards
    events:
      - s3:
          bucket: loyalty-s3bucket-yldevier
          event: s3:ObjectCreated:*
          existing: true

  processLoyaltyCardTask:
    handler: handler.sqs_trigger
    events:
      - sqs:
          arn: arn:aws:sqs:ap-southeast-1:956304645529:yldevier-loyalty-cards-sqs

resources:
  Resources:
    LoyaltyCardsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
